#!/bin/bash
#SBATCH --job-name=process_cubes
#SBATCH --partition=obs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=30G
#SBATCH --time=02:00:00
#SBATCH --output=slurm_script/process_cubes_%A.out
#SBATCH --error=slurm_script/process_cubes_%A.err

module load conda
conda activate /carnegie/scidata/groups/muse_stacking/conda_envs/cassi

python run_pipeline.py --download --field-indices 97 98 99 127 137 \
    --sex-config /carnegie/scidata/groups/muse_stacking/CASSI_26/wl_eso.sex \
    --resume-from mask
