#!/bin/bash
#SBATCH --job-name=process_cubes
#SBATCH --partition=obs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=38G
#SBATCH --time=48:00:00
#SBATCH --output=slurm_script/process_cubes_%A.out
#SBATCH --error=slurm_script/process_cubes_%A.err

module load conda
conda activate /carnegie/scidata/groups/muse_stacking/conda_envs/cassi

python run_pipeline.py --download --n-fields 2 --max-gb 105000 \
    --sex-config /carnegie/scidata/groups/muse_stacking/CASSI_26/wl_eso.sex
