#!/bin/bash
#SBATCH --job-name=process_cubes2
#SBATCH --partition=obs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=38G
#SBATCH --time=24:00:00
#SBATCH --output=slurm_script/process_cubes2_%A.out
#SBATCH --error=slurm_script/process_cubes2_%A.err

module load conda
conda activate /carnegie/scidata/groups/muse_stacking/conda_envs/cassi

cd /carnegie/scidata/groups/muse_stacking/CASSI_26
 
python build_pairs_from_scratch.py \
    --scratch-dir /carnegie/scidata/groups/muse_stacking/CASSI_26/scratch \
    --pairs-path /carnegie/scidata/groups/muse_stacking/CASSI_26/muse_x_milliquas_pairs.fits \
    --sample-path /carnegie/scidata/groups/muse_stacking/CASSI_26/muse_x_milliquas_sample.fits \
    --pairs-out /carnegie/scidata/groups/muse_stacking/CASSI_26/muse_x_milliquas_pairs_local.fits \
    --sex-config /carnegie/scidata/groups/muse_stacking/CASSI_26/wl_eso.sex
